global:
  scrape_interval: 60s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'node'
    file_sd_configs:
      - files:
        - /etc/prometheus/node_targets.yaml
  - job_name: 'ceph'
    static_configs:
      - targets: ['127.0.0.1:9128']

